"""Turn the r2.13 THT board into r2.14: two ATF1502AS-10JU44 instead of four ATF22V10C.

r2.13 was drawn by hand and is not generated by anything, so this script does not rebuild the
board -- it edits it, always starting again from the r2.13 file in git (BASE), so running it twice
gives the same result:

  1. removes the GALs IC2, IC3, IC5 and IC6 and their silkscreen names, but keeps the copper that
     led to them: its loose ends are what the router connects the new pins to;
  2. places both CPLDs in PLCC-44 through-hole sockets, like the DUART IC4, one above the other
     where the three glue GALs stood, with room between them for a PLCC extractor. A socket is
     24.6 mm across and the old IC2 sat in a 24.4 mm gap between the CPU and the ROMs, so it
     cannot go back there. J8, R31, R32 and R16 move left, onto the small logo (removed with its
     "Classic version 2" text); the GAL decoupling C23-C25 and the DUART's C27/C28 line up in one
     column under J9;
  3. adds the JTAG header J9 (the ATF150x is programmed in circuit) and C33, IC2's second 100 nF;
  4. takes the nets of the new parts from the schematic's netlist, not from its own idea of it;
  5. tears up whatever track or via the new copper collides with and cuts the old stubs back;
  6. takes every supply pin of the sockets to its plane through a via of its own.

Step 6 is needed although the sockets are through-hole: the planes keep 0.508 mm from other
nets, and between the socket pins on their 2.54 mm grid that leaves no copper at all, so the
inner-ring supply pins sit in holes of the plane. Each gets a short track to a via beside the
socket, outside the ring of pins (inside it the plane is an island), and a solid connection
instead of thermal spokes; the few with no straight way out are left to cpld_route.py. What is left
unconnected is routed by cpld_route.py with KiCadRoutingTools.

    "C:/Program Files/KiCad/10.0/bin/python.exe" design/tools/cpld_board.py [--suggest]

--suggest prints, for each CPLD, the pin assignment that puts every signal on the pin nearest
to where its net already runs; that is how the PIN lines in code/pld/cpld/*.pld were chosen.
"""
from pathlib import Path
import json, math, os, re, subprocess, sys, tempfile
import xml.etree.ElementTree as ET
import pcbnew as pcb
import wx

# Some r2.13 silkscreen asks for the Futura font. KiCad logs its absence through wx, and in a
# script wx can turn that into a modal message box that nobody will ever click.
wx.Log.EnableLogging(False)

HERE = Path(__file__).resolve().parent
KICAD = HERE.parent / 'kicad'
BOARD = KICAD / 'solderdemon_m68k.kicad_pcb'
SCH = KICAD / 'solderdemon_m68k.kicad_sch'
PLD = HERE.parent.parent / 'code' / 'pld' / 'cpld'
BASE = '9ac13da'                       # r2.13 THT, the last board with the GALs
CLI = os.environ.get('KICAD_CLI', 'C:/Program Files/KiCad/10.0/bin/kicad-cli.exe')
FPLIB = Path(os.environ.get('KICAD10_FOOTPRINT_DIR', Path(sys.executable).parent.parent / 'share/kicad/footprints'))

mm = pcb.FromMM

OLD_GALS = ['IC2', 'IC3', 'IC5', 'IC6']
JUNK_TEXT = {'WATCHDOG', 'GENERAL GLUE LOGIC', 'DUART GLUE LOGIC', 'ADDRESS DECODER',   # the old GALs
             'Classic', 'version 2\n'}                                                   # under IC2 now
JUNK_LOGO = (176.6, 97.6)              # the small rosco logo where J8 and R31/R32 go
REVISION_TEXT = {'Revision 2.13 (DEVELOPMENT)': 'Revision 2.14 (DEVELOPMENT)',
                 'revision 2.13-DEVELOPMENT': 'revision 2.14-DEVELOPMENT'}

SOCKET = 'Package_LCC:PLCC-44_THT-Socket'
CHIPS = {                        # ref: CUPL source, courtyard centre (mm), silkscreen name
    'IC3': ('ic3_glue.pld', (185.30, 67.90), 'GLUE\nWATCHDOG'),
    'IC2': ('ic2_decoder.pld', (185.30, 93.80), 'ADDRESS\nDECODER'),
}
VCC_PINS, GND_PINS = (3, 15, 23, 35), (10, 22, 30, 42)
JTAG_PINS = {7: 'TDI', 13: 'TMS', 32: 'TCK', 38: 'TDO'}
DEDICATED_INPUTS = (1, 2, 43, 44)
CLOCK_PIN = 43
CAP_FP = 'rosco_m68k:C2.5-3'
# One column right of the sockets, under J9, 6 mm apart: the decoupling of IC3 (C23, C24), of
# IC2 (C25, C33) and of the DUART IC4 below (C27, C28). C23-C25 decoupled the GALs; C33 is new.
# Positions are centres (C2.5-3 has its origin in the middle), with the rotation.
COLUMN_X = 201.17                # the centre line of J9
CAPS = {'C33': ((COLUMN_X, 90.60), 0)}
# r2.13 parts that move: ref -> (position, rotation). J8, R31 and R32 go in a row onto the small
# logo, left of the sockets, with R16 under them; the capacitors into the column.
MOVE = {'J8': ((162.80, 93.13), 0), 'R31': ((166.40, 94.40), -90), 'R32': ((170.40, 94.40), -90),
        'R16': ((166.70, 102.60), 0),
        'C23': ((COLUMN_X, 72.60), 0), 'C24': ((COLUMN_X, 78.60), 0), 'C25': ((COLUMN_X, 84.60), 0),
        'C27': ((COLUMN_X, 96.60), 0), 'C28': ((COLUMN_X, 102.60), 0)}
# reference texts: above the moved row, under R16, right of every capacitor in the column
REF_TEXT = {'C7': ((159.10, 90.90), 0), 'J8': ((162.80, 91.20), 0),
            'R31': ((166.40, 88.20), 0), 'R32': ((170.40, 88.20), 0), 'R16': ((166.70, 105.40), 0),
            **{c: ((COLUMN_X + 4.50, y), 0) for c, ((_, y), _r) in
               list(MOVE.items()) + [('C33', ((COLUMN_X, 90.60), 0))] if c.startswith('C')}}
JTAG = ('J9', 'Connector_PinHeader_2.54mm:PinHeader_2x05_P2.54mm_Vertical', (COLUMN_X - 1.27, 58.40))
CLEARANCE = mm(0.2)


def cupl_pins(name):
    """{pin: signal} from the PIN lines of a CUPL source."""
    text = re.sub(r'/\*.*?\*/', ' ', (PLD / name).read_text(), flags=re.S)
    return {int(n): s for n, s in re.findall(r'^\s*PIN\s+(\d+)\s*=\s*(\w+)\s*;', text, flags=re.M)}


def load_base():
    blob = subprocess.run(['git', 'show', f'{BASE}:design/kicad/rosco_m68k.kicad_pcb'], cwd=KICAD,
                          capture_output=True, check=True).stdout
    tmp = Path(tempfile.mkdtemp()) / 'base.kicad_pcb'
    tmp.write_bytes(blob)
    # the design rules and net classes live in the project file, not in the board
    tmp.with_suffix('.kicad_pro').write_bytes(BOARD.with_suffix('.kicad_pro').read_bytes())
    return pcb.LoadBoard(str(tmp))


def save(b):
    """SaveBoard also rewrites the .kicad_pro and .kicad_prl next to the board from whatever
    settings the loaded board carries. Those files belong to the designer (the DRC rules live
    in the .kicad_pro), so they are put back exactly as they were."""
    keep = {p: p.read_bytes() for p in (BOARD.with_suffix('.kicad_pro'), BOARD.with_suffix('.kicad_prl')) if p.exists()}
    pcb.SaveBoard(str(BOARD), b)
    for p, data in keep.items():
        p.write_bytes(data)


# pcbnew in KiCad 10 hands a removed item to Python, and once Python frees it SWIG loses the
# type of every footprint still on the board. Anything taken off the board is kept alive here.
_GRAVE = []


def remove(b, item):
    b.Remove(item)
    _GRAVE.append(item)


def find(b, ref):
    hits = [fp for fp in b.GetFootprints() if fp.GetReference() == ref]
    assert len(hits) <= 1, ref
    return hits[0] if hits else None


def footprint(ref, fpid, value):
    lib, name = fpid.split(':')
    path = FPLIB / f'{lib}.pretty' if lib != 'rosco_m68k' else KICAD / 'rosco_m68k.pretty'
    fp = pcb.FootprintLoad(str(path), name)
    fp.SetFPID(pcb.LIB_ID(lib, name))
    fp.SetReference(ref)
    fp.SetValue(value)
    return fp


def at_mm(x, y):
    return pcb.VECTOR2I(mm(x), mm(y))


# ---- step 1: silkscreen ----------------------------------------------------------------------
def silkscreen(b):
    for fp in list(b.GetFootprints()):
        p = fp.GetPosition()
        if fp.GetReference() == 'REF**' and abs(pcb.ToMM(p.x) - JUNK_LOGO[0]) < 0.5 and abs(pcb.ToMM(p.y) - JUNK_LOGO[1]) < 0.5:
            remove(b, fp)
    for d in list(b.GetDrawings()):
        if isinstance(d, pcb.PCB_TEXT):
            if d.GetText() in JUNK_TEXT:
                remove(b, d)
            elif d.GetText() in REVISION_TEXT:
                d.SetText(REVISION_TEXT[d.GetText()])
    left = {d.GetText() for d in b.GetDrawings() if isinstance(d, pcb.PCB_TEXT)}
    assert not JUNK_TEXT & left, JUNK_TEXT & left
    tb = b.GetTitleBlock()
    tb.SetRevision('2.14-DEV')
    tb.SetDate('2026-09-27')


# ---- track surgery ---------------------------------------------------------------------------
def zone_holds(b, net, layer, pt):
    return any(z.GetNetname() == net and z.IsOnLayer(layer) and z.HitTestFilledArea(layer, pt)
               for z in b.Zones() if not z.GetIsRuleArea())


def prune(b, nets, region=None):
    """Remove every track and via of `nets` that dangles, until none does. With `region`
    (a BOX2I) only copper whose loose end lies inside it goes, so a stub is cut back to the
    edge of the region and no further."""
    removed = 0
    while True:
        by_net = {}
        for t in b.GetTracks():
            if t.GetNetname() in nets:
                by_net.setdefault(t.GetNetname(), []).append(t)
        pads = {}
        for fp in b.GetFootprints():
            for p in fp.Pads():
                if p.GetNetname() in nets:
                    pads.setdefault(p.GetNetname(), []).append(p)
        dead = []
        for net, items in by_net.items():
            vias = [t for t in items if t.Type() == pcb.PCB_VIA_T]
            segs = [t for t in items if t.Type() == pcb.PCB_TRACE_T]
            for v in vias:
                r = v.GetWidth(pcb.F_Cu) // 2
                links = sum(1 for s in segs for e in (s.GetStart(), s.GetEnd()) if (e - v.GetPosition()).EuclideanNorm() <= r)
                links += sum(1 for p in pads.get(net, []) if p.HitTest(v.GetPosition()))
                if links < 2 and not any(zone_holds(b, net, l, v.GetPosition()) for l in v.GetLayerSet().CuStack()) \
                        and (region is None or region.Contains(v.GetPosition())):
                    dead.append(v)
            for s in segs:
                layer = s.GetLayer()
                for e in (s.GetStart(), s.GetEnd()):
                    ok = any(p.IsOnLayer(layer) and p.HitTest(e) for p in pads.get(net, []))
                    ok = ok or any((v.GetPosition() - e).EuclideanNorm() <= v.GetWidth(pcb.F_Cu) // 2 for v in vias)
                    ok = ok or any(o is not s and o.GetLayer() == layer and o.HitTest(e, 0) for o in segs)
                    ok = ok or zone_holds(b, net, layer, e)
                    ok = ok or (region is not None and not region.Contains(e))
                    if not ok:
                        dead.append(s)
                        break
        dead = {t.m_Uuid.AsString(): t for t in dead}
        if not dead:
            return removed
        for t in dead.values():
            remove(b, t)
        removed += len(dead)


def rip_collisions(b, footprints):
    """Remove every track and via that the pads of `footprints` would short or crowd."""
    hit = []
    pads = [p for fp in footprints for p in fp.Pads()]
    for t in b.GetTracks():
        layers = [t.GetLayer()] if t.Type() == pcb.PCB_TRACE_T else list(t.GetLayerSet().CuStack())
        for p in pads:
            # a track of the pad's own net may touch it; a via may not, its hole needs room
            if t.Type() == pcb.PCB_TRACE_T and p.GetNetname() and p.GetNetname() == t.GetNetname():
                continue
            common = [l for l in layers if p.IsOnLayer(l)]
            if any(t.GetEffectiveShape(l).Collide(p.GetEffectiveShape(l), CLEARANCE) for l in common):
                hit.append(t)
                break
    nets = {t.GetNetname() for t in hit}
    for t in hit:
        remove(b, t)
    return nets, len(hit)


# ---- placement -------------------------------------------------------------------------------
def place_centred(fp, x, y):
    """Put a footprint so that its courtyard is centred on (x, y)."""
    fp.SetPosition(at_mm(0, 0))
    c = fp.GetCourtyard(pcb.F_CrtYd).BBox().GetCenter()
    fp.SetPosition(at_mm(x, y) - c)


def place_chip(b, ref):
    pld, (x, y), label = CHIPS[ref]
    fp = footprint(ref, SOCKET, 'ATF1502AS-10JU44')
    b.Add(fp)
    place_centred(fp, x, y)
    # inside the inner ring of pins, which leaves about 9 mm
    fp.Reference().SetPosition(at_mm(x, y - 2.2))
    fp.Reference().SetLayer(pcb.F_SilkS)
    fp.Value().SetVisible(False)
    t = pcb.PCB_TEXT(b)
    t.SetText(label)
    t.SetPosition(at_mm(x, y + 0.9))
    t.SetLayer(pcb.F_SilkS)
    t.SetTextSize(pcb.VECTOR2I(mm(0.9), mm(0.9)))
    t.SetTextThickness(mm(0.15))
    b.Add(t)
    return fp


def place_caps(b):
    out = []
    for ref, ((x, y), rot) in CAPS.items():
        fp = footprint(ref, CAP_FP, '100nF')
        b.Add(fp)
        fp.SetOrientationDegrees(rot)
        fp.SetPosition(at_mm(x, y))
        out.append(fp)
    return out


def move_parts(b):
    out = []
    for ref, ((x, y), rot) in MOVE.items():
        fp = find(b, ref)
        fp.SetOrientationDegrees(rot)
        fp.SetPosition(at_mm(x, y))
        out.append(fp)
    return out


def tidy_refs(b):
    for ref, ((x, y), angle) in REF_TEXT.items():
        if find(b, ref) is None:
            continue                      # a new part, placed after this runs
        t = find(b, ref).Reference()
        t.SetPosition(at_mm(x, y))
        t.SetTextAngleDegrees(angle)
        t.SetHorizJustify(pcb.GR_TEXT_H_ALIGN_CENTER)
        t.SetVertJustify(pcb.GR_TEXT_V_ALIGN_CENTER)
        if ref.startswith('C') and ref != 'C7':      # the column: 3.7 mm between it and R27
            t.SetTextSize(pcb.VECTOR2I(mm(0.9), mm(0.9)))
            t.SetTextThickness(mm(0.15))


def place_jtag(b):
    ref, fpid, (x, y) = JTAG
    fp = footprint(ref, fpid, 'JTAG')
    fp.SetPosition(at_mm(x, y))
    b.Add(fp)
    fp.Reference().SetPosition(at_mm(x + 1.27, y - 2.2))
    fp.Value().SetVisible(False)
    t = pcb.PCB_TEXT(b)
    t.SetText('JTAG')
    t.SetPosition(at_mm(x + 6.0, y + 5.08))
    t.SetTextAngleDegrees(90)
    t.SetLayer(pcb.F_SilkS)
    t.SetTextSize(pcb.VECTOR2I(mm(1.0), mm(1.0)))
    t.SetTextThickness(mm(0.15))
    b.Add(t)
    return fp


# ---- nets ------------------------------------------------------------------------------------
def netlist():
    """{(ref, pin): (net, pinfunction, pintype), ...} and {ref: sheet path} from the schematic."""
    out = Path(tempfile.mkdtemp()) / 'solderdemon_m68k.xml'
    subprocess.run([CLI, 'sch', 'export', 'netlist', '--format', 'kicadxml', '-o', str(out), str(SCH)],
                   check=True, capture_output=True)
    root = ET.parse(out).getroot()
    pins = {}
    for net in root.iter('net'):
        for node in net.iter('node'):
            pins[(node.get('ref'), node.get('pin'))] = (net.get('name'), node.get('pinfunction') or '',
                                                       node.get('pintype') or '')
    comps = {}
    for c in root.iter('comp'):
        sp = c.find('sheetpath')
        comps[c.get('ref')] = (sp.get('tstamps') + c.find('tstamps').text, sp.get('names'),
                               c.find('value').text, c.find('footprint').text)
    return pins, comps


def apply_nets(b, footprints, pins, comps):
    for fp in footprints:
        ref = fp.GetReference()
        path, sheet, value, fpid = comps[ref]
        assert fpid == fp.GetFPIDAsString(), (ref, fpid, fp.GetFPIDAsString())
        fp.SetPath(pcb.KIID_PATH(path))
        fp.SetValue(value)
        if hasattr(fp, 'SetSheetname'):
            fp.SetSheetname(sheet.strip('/').split('/')[-1] if sheet != '/' else '')
        for p in fp.Pads():
            net, func, kind = pins.get((ref, p.GetNumber()), ('', '', ''))
            if not net:
                p.SetNetCode(0)
                continue
            net = net.replace('/', '{slash}')       # how the board spells '/' in a net name
            ni = b.FindNet(net)
            if ni is None:
                ni = pcb.NETINFO_ITEM(b, net)
                b.Add(ni)
            p.SetNet(ni)
            p.SetPinFunction(func)
            p.SetPinType(kind)


def check_all_nets(b, pins):
    """Every pad on the board has the net the schematic gives it."""
    bad = []
    for fp in b.GetFootprints():
        for p in fp.Pads():
            key = (fp.GetReference(), p.GetNumber())
            want = pins.get(key, ('',))[0]
            if key in pins and not want.startswith('unconnected-') and want != p.GetNetname().replace('{slash}', '/'):
                bad.append((key, p.GetNetname(), want))
    assert not bad, bad[:20]


# ---- --suggest -------------------------------------------------------------------------------
def hungarian(cost):
    """Minimum-cost assignment of rows to columns (rows <= columns). Returns {row: col}."""
    n, m = len(cost), len(cost[0])
    INF = float('inf')
    u, v, p, way = [0.0] * (n + 1), [0.0] * (m + 1), [0] * (m + 1), [0] * (m + 1)
    for i in range(1, n + 1):
        p[0], j0 = i, 0
        minv, used = [INF] * (m + 1), [False] * (m + 1)
        while True:
            used[j0] = True
            i0, delta, j1 = p[j0], INF, 0
            for j in range(1, m + 1):
                if not used[j]:
                    cur = cost[i0 - 1][j - 1] - u[i0] - v[j]
                    if cur < minv[j]:
                        minv[j], way[j] = cur, j0
                    if minv[j] < delta:
                        delta, j1 = minv[j], j
            for j in range(m + 1):
                if used[j]:
                    u[p[j]] += delta; v[j] -= delta
                else:
                    minv[j] -= delta
            j0 = j1
            if p[j0] == 0:
                break
        while True:
            j1 = way[j0]; p[j0] = p[j1]; j0 = j1
            if j0 == 0:
                break
    return {p[j] - 1: j - 1 for j in range(1, m + 1) if p[j]}


OUTPUTS = {'EVENRAMSEL', 'ODDRAMSEL', 'EVENROMSEL', 'ODDROMSEL', 'IOSEL', 'EXPSEL', 'DTACK', 'WR',
           'DUASEL', 'DUAIACK', 'HALT', 'RESET', 'RUNLED', 'BERR'}


def suggest(b, chips):
    """Put each signal on the free pin closest to the nearest copper its net already has."""
    for fp in chips:
        ref = fp.GetReference()
        pins = cupl_pins(CHIPS[ref][0])
        driven = OUTPUTS if ref == 'IC3' else OUTPUTS - {'HALT', 'RESET'}
        pads = {int(p.GetNumber()): p.GetPosition() for p in fp.Pads()}
        fixed = {n: s for n, s in pins.items() if n == CLOCK_PIN}
        sigs = [s for n, s in sorted(pins.items()) if n not in fixed]
        slots = [n for n in pads if n not in VCC_PINS + GND_PINS and n not in JTAG_PINS and n not in fixed]
        others = [f for f in b.GetFootprints() if f.GetReference() not in CHIPS]
        cost = []
        for s in sigs:
            pts = [p.GetPosition() for f in others for p in f.Pads() if p.GetNetname() == s]
            pts += [e for t in b.GetTracks() if t.GetNetname() == s
                    for e in ((t.GetPosition(),) if t.Type() == pcb.PCB_VIA_T else (t.GetStart(), t.GetEnd()))]
            assert pts, f'{s} has no copper on the board'
            row = []
            for n in slots:
                if n in DEDICATED_INPUTS and s in driven:
                    row.append(1e9); continue
                row.append(min((pads[n] - q).EuclideanNorm() for q in pts) / 1e6)
            cost.append(row)
        best = hungarian(cost)
        print(f'/* {ref}: suggested pins */')
        for n, s in sorted({**fixed, **{slots[best[i]]: s for i, s in enumerate(sigs)}}.items()):
            print(f'PIN {n:<2} = {s};')


def plane_vias(b, footprints):
    """Connect every VCC/GND pad of `footprints` to its plane with a short track to a via, the
    via as close to the pad as the copper around allows, away from the middle of the part first:
    the ring of socket pins cuts the plane inside it off from the rest. A pad with no straight
    way out is returned, for cpld_route.py to connect with KiCadRoutingTools' repair_planes."""
    via_d, drill, width, gap, hole_gap = mm(0.6), mm(0.3), mm(0.3), mm(0.2), mm(0.3)
    added, left = 0, []
    for fp in footprints:
        centre = fp.GetCourtyard(pcb.F_CrtYd).BBox().GetCenter()
        # the via has to land outside the ring of pins, clear of the outermost pads
        ring = max(max(abs(q.GetPosition().x - centre.x), abs(q.GetPosition().y - centre.y)) for q in fp.Pads())
        ring += max(q.GetSize(pcb.F_Cu).x for q in fp.Pads()) // 2 + via_d // 2 + gap
        for pad in fp.Pads():
            net = pad.GetNetname()
            if net not in ('VCC', 'GND'):
                continue
            pad.SetLocalZoneConnection(pcb.ZONE_CONNECTION_FULL)
            p = pad.GetPosition()
            outward = math.atan2(p.y - centre.y, p.x - centre.x)
            area = pcb.BOX2I(p - pcb.VECTOR2I(mm(5), mm(5)), pcb.VECTOR2L(mm(10), mm(10)))
            near = [o for o in list(b.GetTracks()) + [q for f in b.GetFootprints() for q in f.Pads()]
                    if o is not pad and o.GetBoundingBox().Intersects(area)]
            holes = [o for o in near if (o.Type() == pcb.PCB_VIA_T or
                                         (o.Type() == pcb.PCB_PAD_T and o.GetDrillSize().x > 0))]
            done = False
            tries = [(dist, k, layer) for dist in (1.8, 2.2, 2.6, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
                     for layer in (pcb.B_Cu, pcb.F_Cu)
                     for k in sorted(range(-36, 36), key=abs)]
            for dist, k, layer in tries:
                    a = outward + k * math.pi / 36
                    at = p + pcb.VECTOR2I(int(mm(dist) * math.cos(a)), int(mm(dist) * math.sin(a)))
                    if max(abs(at.x - centre.x), abs(at.y - centre.y)) < ring:
                        continue
                    v = pcb.PCB_VIA(b)
                    v.SetPosition(at); v.SetWidth(via_d); v.SetDrill(drill)
                    v.SetLayerPair(pcb.F_Cu, pcb.B_Cu); v.SetNet(pad.GetNet())
                    t = pcb.PCB_TRACK(b)
                    t.SetStart(p); t.SetEnd(at); t.SetWidth(width); t.SetLayer(layer); t.SetNet(pad.GetNet())
                    clash = False
                    for o in near:
                        if o.GetNetname() == net:
                            continue
                        for l in (pcb.F_Cu, pcb.B_Cu):
                            if not o.IsOnLayer(l):
                                continue
                            os_ = o.GetEffectiveShape(l)
                            if v.GetEffectiveShape(l).Collide(os_, gap) or                                     (l == layer and t.GetEffectiveShape(l).Collide(os_, gap)):
                                clash = True
                                break
                        if clash:
                            break
                    for o in holes:                      # holes of any net, this pad's own too
                        r = (o.GetDrillSize().x if o.Type() == pcb.PCB_PAD_T else o.GetDrill()) // 2
                        if (o.GetPosition() - at).EuclideanNorm() < r + drill // 2 + hole_gap:
                            clash = True
                    if (pad.GetPosition() - at).EuclideanNorm() < pad.GetDrillSize().x // 2 + drill // 2 + hole_gap:
                        clash = True
                    if not clash:
                        b.Add(v); b.Add(t)
                        added += 1
                        done = True
                        break
            if not done:
                left.append(f'{fp.GetReference()}.{pad.GetNumber()}')
    return added, left


def drc(extra=()):
    save_path = BOARD
    rpt = Path(tempfile.mkdtemp()) / 'drc.json'
    subprocess.run([CLI, 'pcb', 'drc', '--format', 'json', *extra, '-o', str(rpt), str(save_path)], capture_output=True)
    return json.loads(rpt.read_text(encoding='utf-8'))


def main():
    b = load_base()
    silkscreen(b)
    gal_nets = {p.GetNetname() for r in OLD_GALS for p in find(b, r).Pads()} - {'', 'GND', 'VCC'}
    for r in OLD_GALS:
        remove(b, find(b, r))
    # Nets that lived purely between the GALs (BOOT, ANYIACK) are internal to IC2 now: their
    # copper goes. The rest stays, its loose ends are where the new pins get connected.
    padded = {p.GetNetname() for fp in b.GetFootprints() for p in fp.Pads()}
    orphans = [t for t in b.GetTracks() if t.GetNetname() in gal_nets - padded]
    for t in orphans:
        remove(b, t)
    print('tracks of nets that only ran between the GALs:', len(orphans), sorted(gal_nets - padded))
    moved = move_parts(b)
    tidy_refs(b)
    chips = [place_chip(b, r) for r in CHIPS]
    if '--suggest' in sys.argv:
        return suggest(b, chips)
    caps = place_caps(b)
    tidy_refs(b)
    jtag = place_jtag(b)
    new = chips + caps + [jtag]
    pins, comps = netlist()
    apply_nets(b, new, pins, comps)
    check_all_nets(b, pins)
    nets, n = rip_collisions(b, new + moved)
    print(f'tracks and vias in the way of the new and moved parts: {n} on {len(nets)} nets')
    # cut the loose ends left by the GAL pins and by the rip-up back to the edge of the sockets
    cut = 0
    for fp in chips:
        box = fp.GetCourtyard(pcb.F_CrtYd).BBox()
        box.Inflate(mm(0.5))
        cut += prune(b, (gal_nets | nets) - {'GND', 'VCC'}, region=box)
    print('old stubs cut back to the edge of the sockets:', cut)
    n, left = plane_vias(b, chips)
    print('socket supply pins taken to the planes:', n, '; left to repair_planes:', left)
    pcb.ZONE_FILLER(b).Fill(b.Zones())
    save(b)
    b.BuildConnectivity()
    print('unconnected before routing:', b.GetConnectivity().GetUnconnectedCount(True))


if __name__ == '__main__':
    main()
